/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import ConexionBD.Conexion;
import InterfazClientes.ClientesMenu;
import NuevosDatos_Entidades.NuevosClientes;
import java.awt.Color;
import java.awt.Image;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author danielferova
 */
public class AccesoClientes extends javax.swing.JFrame {
    protected ArrayList<String> tablaTienda= new ArrayList<>();
    String Icono =  "logo2.png";
    

    /**
     * Creates new form Inicio
     */
    public AccesoClientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.ORANGE);
        cargarIcono(Icono);
        nuevosClientes = new NuevosClientes();
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intelaf = new javax.swing.JLabel();
        nitC = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        accederC = new javax.swing.JButton();
        nombreCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sesion");
        setBackground(new java.awt.Color(0, 255, 51));
        setForeground(new java.awt.Color(102, 255, 51));

        intelaf.setText("jLabel3");

        nitC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nitCActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 241, 241));
        jLabel2.setText("NIT CLIENTE:");

        accederC.setBackground(new java.awt.Color(5, 0, 0));
        accederC.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        accederC.setForeground(new java.awt.Color(245, 235, 235));
        accederC.setText("ACCEDER");
        accederC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederCActionPerformed(evt);
            }
        });

        nombreCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:" }));
        nombreCliente.setToolTipText("");
        nombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(accederC, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intelaf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nitC, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(147, 147, 147))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(intelaf, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nitC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(accederC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nitCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nitCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nitCActionPerformed

    private void llenarCombo() {
        
        Conexion conexion = new Conexion();
        ResultSet rs = conexion.getTabla("SELECT Nombre_Cliente, Nit_Cliente FROM CLIENTE");
        try {
            while (rs.next()) {
                nombreCliente.addItem(rs.getString(1));
                tablaTienda.add(rs.getString(2));
            }

        } catch (Exception e) {

        }
    }
    
    private void accederCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederCActionPerformed
        //Para poder ingresar la contraseña, el id_Empleado
         if(nombreCliente.getSelectedIndex()!=0){
        ClientesMenu accesarAlMenu = new ClientesMenu(nombreCliente.getItemAt(nombreCliente.getSelectedIndex()),tablaTienda.get(nombreCliente.getSelectedIndex()-1));
        accesarAlMenu.setVisible(true);
        this.setVisible(false);
        } else
        {
            JOptionPane.showMessageDialog(null, "ERROR SELECIONE UN CLIENTE");
                   
        }
        
        
       /* if(nitC.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "-- INGRESE SU NIT ---" );
        }else{
            if(nuevosClientes.existeCliente(nitC.getText())){
                nitC.setText("");
                ClientesMenu menuClientes = new ClientesMenu();
                //para pasar el nombre del empleado
                //menuEmpleados.getNombreEmpleado().setText(nuevosClientes.llamarNombreEmpleado(nameEmpleados.getSelectedItem().toString()));
                this.setVisible(false);
                menuClientes.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "-- ERROR NIT INCORRECTO --");
                nitC.setText("");
            }
        }*/
    }//GEN-LAST:event_accederCActionPerformed

    private void nombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreClienteActionPerformed

     public void cargarIcono(String NombreImagen)
    {
        ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(intelaf.getWidth(), intelaf.getHeight(), Image.SCALE_DEFAULT));
        intelaf.setIcon(imageIconFinal);
    }
    

      NuevosClientes nuevosClientes; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accederC;
    private javax.swing.JLabel intelaf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField nitC;
    private javax.swing.JComboBox<String> nombreCliente;
    // End of variables declaration//GEN-END:variables
}
