/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import EntidadesMapeo.EMPLEADO;
import EntidadesMapeo.TIENDA;
import NuevosDatos_Entidades.NuevosEmpleados;
import NuevosDatos_Entidades.NuevosTienda;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author danielferova
 */
public class IngresarUsuario extends javax.swing.JFrame {
     String imagen =  "intelaf2.png";
    /**
     * Creates new form usuarios
     */
    public IngresarUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.ORANGE);
        cargarIcono(imagen);
        nuevosEmpleados = new NuevosEmpleados();
        insertarNombresE(nuevosEmpleados.llamarNombreEmpleado());
    }
    //para llamar a mis imagenes
    public void cargarIcono(String NombreImagen)
    {
       ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(intelaf.getWidth(), intelaf.getHeight(), Image.SCALE_DEFAULT));
        intelaf.setIcon(imageIconFinal);
    }
   
     //para ver si existe mis datos de empleado
     public EMPLEADO verificarEstadoBD(){
            NuevosEmpleados existeTienda = new NuevosEmpleados();
            EMPLEADO t = existeTienda.obtenerEmpleado();
         return t;
        
        }
     //agregar nombres
       public void insertarNombresE(ArrayList<String> nombres){
        for (int i = 0; i < nombres.size(); i++) {
            nameEmpleados.addItem(nombres.get(i));
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acceder = new javax.swing.JButton();
        intelaf = new javax.swing.JLabel();
        nameEmpleados = new javax.swing.JComboBox<>();
        contraseña = new javax.swing.JPasswordField();
        iniciarC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbNombre.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jlbNombre.setForeground(new java.awt.Color(254, 247, 247));
        jlbNombre.setText("NOMBRE:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 241, 241));
        jLabel2.setText("CONTRASEÑA:");

        acceder.setBackground(new java.awt.Color(5, 0, 0));
        acceder.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        acceder.setForeground(new java.awt.Color(245, 235, 235));
        acceder.setText("ACCEDER");
        acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accederActionPerformed(evt);
            }
        });

        intelaf.setText("jLabel3");

        nameEmpleados.setBackground(new java.awt.Color(254, 247, 247));
        nameEmpleados.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        nameEmpleados.setForeground(new java.awt.Color(4, 2, 2));
        nameEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEmpleadosActionPerformed(evt);
            }
        });

        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });

        iniciarC.setBackground(new java.awt.Color(18, 8, 8));
        iniciarC.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        iniciarC.setForeground(new java.awt.Color(244, 240, 240));
        iniciarC.setText("CLIENTES");
        iniciarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(intelaf, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbNombre)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(acceder, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iniciarC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(intelaf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbNombre))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(acceder, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(iniciarC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accederActionPerformed
        //Para poder ingresar la contraseña, el id_Empleado
        if(contraseña.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "-- Ingrese su Contraseña ---" );
        }else{
            if(nuevosEmpleados.existeEmpleado(contraseña.getText())){
                contraseña.setText("");
                EmpleadosMenu menuEmpleados = new EmpleadosMenu();
                //para pasar el nombre del empleado 
                menuEmpleados.getNombreEmpleado().setText(nuevosEmpleados.llamarNombreEmpleado(nameEmpleados.getSelectedItem().toString()));
                this.setVisible(false);
                menuEmpleados.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "-- Error contraseña incorrecta --");
                contraseña.setText("");
            }
        }
    }//GEN-LAST:event_accederActionPerformed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaActionPerformed

    private void nameEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEmpleadosActionPerformed

    private void iniciarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarCActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AccesoClientes llamandoC = new AccesoClientes();
        llamandoC.setVisible(true);
    }//GEN-LAST:event_iniciarCActionPerformed
 NuevosEmpleados nuevosEmpleados; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceder;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JButton iniciarC;
    private javax.swing.JLabel intelaf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlbNombre;
    public javax.swing.JComboBox<String> nameEmpleados;
    // End of variables declaration//GEN-END:variables
}
