/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import EntidadesMapeo.CLIENTE;
import NuevosDatos_Entidades.NuevosClientes;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author danielferova
 */
public class IngresarClientes extends javax.swing.JInternalFrame {

    /**
     * Ingresar Clientes
     */
    public IngresarClientes() {
        initComponents();
        this.getContentPane().setBackground(Color.ORANGE);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        nombreC = new javax.swing.JTextField();
        lblCodigoFabricante = new javax.swing.JLabel();
        telefonoC = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        nitC = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        creditoC = new javax.swing.JTextField();
        lblGarantia = new javax.swing.JLabel();
        direccionC = new javax.swing.JTextField();
        correoC = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        registrarClientes = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        dpiC = new javax.swing.JTextField();
        lblGarantia1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 132, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ingresar Cliente");

        lblNombre.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(254, 254, 254));
        lblNombre.setText("Nombre:");

        nombreC.setBackground(new java.awt.Color(254, 254, 254));
        nombreC.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        nombreC.setForeground(new java.awt.Color(1, 1, 1));
        nombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCActionPerformed(evt);
            }
        });

        lblCodigoFabricante.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCodigoFabricante.setForeground(new java.awt.Color(254, 247, 247));
        lblCodigoFabricante.setText("Teléfono:");

        telefonoC.setBackground(new java.awt.Color(254, 254, 254));
        telefonoC.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        telefonoC.setForeground(new java.awt.Color(1, 1, 1));
        telefonoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoCActionPerformed(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(254, 254, 254));
        lblCodigo.setText("NIT:");

        nitC.setBackground(new java.awt.Color(254, 254, 254));
        nitC.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        nitC.setForeground(new java.awt.Color(1, 1, 1));

        lblPrecio.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(254, 254, 254));
        lblPrecio.setText("Crédito Compra:");

        creditoC.setBackground(new java.awt.Color(254, 254, 254));
        creditoC.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        creditoC.setForeground(new java.awt.Color(1, 1, 1));

        lblGarantia.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblGarantia.setForeground(new java.awt.Color(254, 254, 254));
        lblGarantia.setText("Dirección:");

        direccionC.setBackground(new java.awt.Color(254, 254, 254));
        direccionC.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        direccionC.setForeground(new java.awt.Color(1, 1, 1));

        correoC.setBackground(new java.awt.Color(254, 254, 254));
        correoC.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        correoC.setForeground(new java.awt.Color(1, 1, 1));

        lblDescripcion.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(254, 254, 254));
        lblDescripcion.setText("Correo Eléctronico:");

        registrarClientes.setBackground(new java.awt.Color(1, 1, 1));
        registrarClientes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        registrarClientes.setForeground(new java.awt.Color(254, 254, 254));
        registrarClientes.setText("Registrar Clientes");
        registrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClientesActionPerformed(evt);
            }
        });

        regresar.setBackground(new java.awt.Color(1, 1, 1));
        regresar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        regresar.setForeground(new java.awt.Color(254, 254, 254));
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        dpiC.setBackground(new java.awt.Color(254, 254, 254));
        dpiC.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        dpiC.setForeground(new java.awt.Color(1, 1, 1));

        lblGarantia1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblGarantia1.setForeground(new java.awt.Color(253, 251, 251));
        lblGarantia1.setText("DPI:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(registrarClientes)
                .addGap(534, 534, 534))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGarantia)
                    .addComponent(lblCodigoFabricante)
                    .addComponent(lblNombre)
                    .addComponent(lblCodigo)
                    .addComponent(lblGarantia1)
                    .addComponent(lblPrecio)
                    .addComponent(lblDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreC, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(nitC)
                    .addComponent(telefonoC)
                    .addComponent(creditoC)
                    .addComponent(dpiC)
                    .addComponent(direccionC, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addComponent(correoC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nitC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoFabricante)
                    .addComponent(telefonoC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(creditoC, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGarantia1)
                    .addComponent(dpiC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(correoC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGarantia)
                    .addComponent(direccionC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telefonoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoCActionPerformed

    private void registrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClientesActionPerformed

        String nombre = nombreC.getText();
        String nit = nitC.getText();
        String telefono = telefonoC.getText();
        Double creditoCompra = 0.0;
        if(!creditoC.getText().equals("")){
            creditoCompra = Double.parseDouble(creditoC.getText());
        }
        String dpi = dpiC.getText();
        String correo = correoC.getText();
        String direccion = direccionC.getText();
        
        if(nombre.equals("") || nit.equals("") || telefono.equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese CAMPOS OBLIGATORIOS");
        }else{
            CLIENTE ingresar = new CLIENTE(nombre, nit, telefono, creditoCompra, dpi, correo, direccion);
            NuevosDatos_Entidades.NuevosClientes llamar = new NuevosClientes();
            if(!llamar.agregarClientes(ingresar))
                {
                   JOptionPane.showMessageDialog(null, "ERROR NO SE PUEDE INGRESAR" + nombre + "Datos errones o repetidos"+ nit + "Datos errones o repetidos" 
                           + telefono + "Datos errones o repetidos" + creditoCompra + "Datos errones o repetidos" + dpi + "Datos errones o repetidos" + correo + "Datos errones o repetidos" + direccion +"Datos errones o repetidos");
                   
                }else{
                JOptionPane.showMessageDialog(null, "CLIENTE agregado");
                EmpleadosMenu regresar = new EmpleadosMenu();
                regresar.setVisible(true);
                this.setVisible(false);
            }
        }
        
        
    }//GEN-LAST:event_registrarClientesActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarActionPerformed

    private void nombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField correoC;
    private javax.swing.JTextField creditoC;
    private javax.swing.JTextField direccionC;
    private javax.swing.JTextField dpiC;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoFabricante;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblGarantia;
    private javax.swing.JLabel lblGarantia1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTextField nitC;
    private javax.swing.JTextField nombreC;
    private javax.swing.JButton registrarClientes;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField telefonoC;
    // End of variables declaration//GEN-END:variables
}
