/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import EntidadesMapeo.EMPLEADO;
import NuevosDatos_Entidades.NuevosEmpleados;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author danielferova
 */
public class IngresarEmpleados extends javax.swing.JInternalFrame {

    /**
     * Ingresar Empleados
     */
    public IngresarEmpleados() {
        initComponents();
        this.getContentPane().setBackground(Color.ORANGE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarE = new javax.swing.JButton();
        regresarE = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        nombreEmplead = new javax.swing.JTextField();
        lblCodigoFabricante = new javax.swing.JLabel();
        telefonoE = new javax.swing.JTextField();
        lblGarantia1 = new javax.swing.JLabel();
        nitE = new javax.swing.JTextField();
        lbCorreo = new javax.swing.JLabel();
        correoE = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        contraseñaE = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        dpiE = new javax.swing.JTextField();
        lblGarantia = new javax.swing.JLabel();
        direccionE = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 116, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ingresar Empleado");

        registrarE.setBackground(new java.awt.Color(1, 1, 1));
        registrarE.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        registrarE.setForeground(new java.awt.Color(254, 254, 254));
        registrarE.setText("Registrar Empleado");
        registrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEActionPerformed(evt);
            }
        });

        regresarE.setBackground(new java.awt.Color(1, 1, 1));
        regresarE.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        regresarE.setForeground(new java.awt.Color(254, 254, 254));
        regresarE.setText("Regresar");
        regresarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarEActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(254, 254, 254));
        lblNombre.setText("Nombre:");

        nombreEmplead.setBackground(new java.awt.Color(254, 254, 254));
        nombreEmplead.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        nombreEmplead.setForeground(new java.awt.Color(1, 1, 1));

        lblCodigoFabricante.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCodigoFabricante.setForeground(new java.awt.Color(254, 247, 247));
        lblCodigoFabricante.setText("Teléfono:");

        telefonoE.setBackground(new java.awt.Color(254, 254, 254));
        telefonoE.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        telefonoE.setForeground(new java.awt.Color(1, 1, 1));
        telefonoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoEActionPerformed(evt);
            }
        });

        lblGarantia1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblGarantia1.setForeground(new java.awt.Color(253, 251, 251));
        lblGarantia1.setText("NIT:");

        nitE.setBackground(new java.awt.Color(254, 254, 254));
        nitE.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        nitE.setForeground(new java.awt.Color(1, 1, 1));

        lbCorreo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lbCorreo.setForeground(new java.awt.Color(254, 254, 254));
        lbCorreo.setText("Correo Electrónico:");

        correoE.setBackground(new java.awt.Color(254, 254, 254));
        correoE.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        correoE.setForeground(new java.awt.Color(1, 1, 1));

        lblCodigo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(254, 254, 254));
        lblCodigo.setText("Contraseña:");

        contraseñaE.setBackground(new java.awt.Color(254, 254, 254));
        contraseñaE.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        contraseñaE.setForeground(new java.awt.Color(1, 1, 1));

        lblPrecio.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(254, 254, 254));
        lblPrecio.setText("DPI:");

        dpiE.setBackground(new java.awt.Color(254, 254, 254));
        dpiE.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        dpiE.setForeground(new java.awt.Color(1, 1, 1));

        lblGarantia.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblGarantia.setForeground(new java.awt.Color(254, 254, 254));
        lblGarantia.setText("Dirección:");

        direccionE.setBackground(new java.awt.Color(254, 254, 254));
        direccionE.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        direccionE.setForeground(new java.awt.Color(1, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(regresarE, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(registrarE, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(lbCorreo)
                .addGap(18, 18, 18)
                .addComponent(correoE, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreEmplead))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCodigoFabricante, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblPrecio, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(lblGarantia1)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nitE, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(telefonoE)
                                    .addComponent(contraseñaE, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dpiE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblGarantia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccionE, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombre)
                    .addComponent(nombreEmplead, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contraseñaE, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoFabricante)
                    .addComponent(telefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(dpiE, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGarantia1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(nitE, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGarantia))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarE, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresarE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEActionPerformed
        // TODO add your handling code here:
        String nombreE = nombreEmplead.getText();
        String codigo = contraseñaE.getText();
        String telefonoEmpleado = telefonoE.getText();
        String dpi = dpiE.getText();
        String nit = nitE.getText();
        String correo = correoE.getText();
        String direccion = direccionE.getText();
        
        if(nombreE.equals("") || codigo.equals("") || telefonoEmpleado.equals("") || dpi.equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese CAMPOS OBLIGATORIOS");
        }else{
            EMPLEADO ingresar = new EMPLEADO(nombreE, codigo,telefonoEmpleado, dpi, nit, correo, direccion);
            NuevosDatos_Entidades.NuevosEmpleados llamar = new NuevosEmpleados();
            if(!llamar.registrarEmpleado(ingresar))
                {
                   JOptionPane.showMessageDialog(null, "ERROR NO SE PUEDE INGRESAR" + nombreE + "Datos errones o repetidos"+ codigo + "Datos errones o repetidos" 
                           + telefonoEmpleado + "Datos errones o repetidos" + dpi + "Datos errones o repetidos" + nit + "Datos errones o repetidos" + correo + "Datos errones o repetidos" + direccion +"Datos errones o repetidos");
                   
                }else{
                JOptionPane.showMessageDialog(null, "EMPLEADO agregado");
                EmpleadosMenu regresar = new EmpleadosMenu();
                regresar.setVisible(true);
                this.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_registrarEActionPerformed

    private void regresarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarEActionPerformed

    private void clienteNombrnombreEmpleadomed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteNombreActionPerformed

    private void telefonoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contraseñaE;
    private javax.swing.JTextField correoE;
    private javax.swing.JTextField direccionE;
    private javax.swing.JTextField dpiE;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoFabricante;
    private javax.swing.JLabel lblGarantia;
    private javax.swing.JLabel lblGarantia1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTextField nitE;
    private javax.swing.JTextField nombreEmplead;
    private javax.swing.JButton registrarE;
    private javax.swing.JButton regresarE;
    private javax.swing.JTextField telefonoE;
    // End of variables declaration//GEN-END:variables
}
