/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author danielferova
 */
public class IngresarTiempo extends javax.swing.JInternalFrame {

    /**
     * Ingresar Tiempo
     */
    public IngresarTiempo() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        tiempoDias = new javax.swing.JTextField();
        lblPrecio1 = new javax.swing.JLabel();
        codigoTienda1 = new javax.swing.JComboBox<>();
        codigoTienda2 = new javax.swing.JComboBox<>();
        regresar = new javax.swing.JButton();
        registrarClientes = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 122, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ingresar Tiempo\n");

        lblNombre.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(254, 254, 254));
        lblNombre.setText("Código Tienda1:");

        lblNombre1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(254, 254, 254));
        lblNombre1.setText("Código Tienda2:");

        tiempoDias.setBackground(new java.awt.Color(253, 251, 251));
        tiempoDias.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tiempoDias.setForeground(new java.awt.Color(1, 1, 1));

        lblPrecio1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblPrecio1.setForeground(new java.awt.Color(254, 254, 254));
        lblPrecio1.setText("Tiempo (Días):");

        codigoTienda1.setBackground(new java.awt.Color(254, 254, 254));
        codigoTienda1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        codigoTienda1.setForeground(new java.awt.Color(1, 1, 1));
        codigoTienda1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                codigoTienda1ItemStateChanged(evt);
            }
        });
        codigoTienda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoTienda1MouseClicked(evt);
            }
        });

        codigoTienda2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N

        regresar.setBackground(new java.awt.Color(1, 1, 1));
        regresar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        regresar.setForeground(new java.awt.Color(254, 254, 254));
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        registrarClientes.setBackground(new java.awt.Color(1, 1, 1));
        registrarClientes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        registrarClientes.setForeground(new java.awt.Color(254, 254, 254));
        registrarClientes.setText("Registrar Tiempo");
        registrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre1)
                                    .addComponent(lblNombre))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(codigoTienda2, 0, 586, Short.MAX_VALUE)
                                    .addComponent(codigoTienda1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrecio1)
                                .addGap(18, 18, 18)
                                .addComponent(tiempoDias, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210)
                        .addComponent(registrarClientes)
                        .addGap(398, 398, 398))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre1)
                            .addComponent(codigoTienda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(codigoTienda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio1)
                    .addComponent(tiempoDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoTienda1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_codigoTienda1ItemStateChanged
        // TODO add your handling code here:
       // agregarNombresTiendas2(dBConectorTienda.recuperarTiendas());
    }//GEN-LAST:event_codigoTienda1ItemStateChanged

    private void codigoTienda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoTienda1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoTienda1MouseClicked

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regresarActionPerformed

    private void registrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarClientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> codigoTienda1;
    private javax.swing.JComboBox<String> codigoTienda2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JButton registrarClientes;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField tiempoDias;
    // End of variables declaration//GEN-END:variables
}
