/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import ConexionBD.Conexion;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author danielferova
 */
public class NuevosPedidos extends javax.swing.JInternalFrame {
     PreparedStatement ps = null;
     
     ResultSet rs = null;
    /**
     * Creates new form NuevosPedidos
     */
    public NuevosPedidos() {
        initComponents();
        this.getContentPane().setBackground(Color.ORANGE);
        comboTienda();
        comboCodigoCliente();
        comboNombreP();
        
    }
    
        private void comboTienda() {

        Conexion conexion = new Conexion();
        ResultSet rs = conexion.getTabla("SELECT Id_Tienda FROM TIENDA");
        try {
            while (rs.next()) {
                comboTienda.addItem(rs.getString(1));
            }

        } catch (Exception e) {

        }
    }
        
            private void comboCodigoCliente() {

        Conexion conexion = new Conexion();
        ResultSet rs = conexion.getTabla("SELECT Nit_Cliente FROM CLIENTE");
        try {
            while (rs.next()) {
                codigoCliente.addItem(rs.getString(1));
            }

        } catch (Exception e) {

        }
    }
          private void comboNombreP() {

        Conexion conexion = new Conexion();
        ResultSet rs = conexion.getTabla("SELECT Nombre_Producto FROM PRODUCTO");
        try {
            while (rs.next()) {
                nombreProducto.addItem(rs.getString(1));
            }

        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblCodigoFabricante = new javax.swing.JLabel();
        ventaCantidad = new javax.swing.JTextField();
        productoDescripcion = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        registrarProducto = new javax.swing.JButton();
        lblCodigoFabricante1 = new javax.swing.JLabel();
        codigoCliente = new javax.swing.JComboBox<>();
        lblNombre1 = new javax.swing.JLabel();
        ventaFecha = new com.toedter.calendar.JDateChooser();
        nombreProducto = new javax.swing.JComboBox<>();
        lblCodigoFabricante2 = new javax.swing.JLabel();
        lblCodigoFabricante4 = new javax.swing.JLabel();
        lblCodigoFabricante6 = new javax.swing.JLabel();
        comboTienda = new javax.swing.JComboBox<>();
        lblCodigoFabricante7 = new javax.swing.JLabel();
        ventaExitencia = new javax.swing.JLabel();
        ventaNombreCliente = new javax.swing.JLabel();
        ventaPrecio = new javax.swing.JLabel();
        ventaPrecio1 = new javax.swing.JLabel();
        lblCodigoFabricante5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblCodigoFabricante8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 101, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("NUEVOS PEDIDOS\n");

        lblNombre.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblNombre.setText("Producto:");

        lblCodigoFabricante.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigoFabricante.setText("Inventario:");

        ventaCantidad.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        ventaCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaCantidadActionPerformed(evt);
            }
        });

        productoDescripcion.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N

        lblDescripcion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblDescripcion.setText("Descripcion:");

        registrarProducto.setBackground(new java.awt.Color(102, 255, 0));
        registrarProducto.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        registrarProducto.setText("Registrar");
        registrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProductoActionPerformed(evt);
            }
        });

        lblCodigoFabricante1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigoFabricante1.setText("Código Cliente:");

        codigoCliente.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N

        lblNombre1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lblNombre1.setText("Fecha:");

        nombreProducto.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N

        lblCodigoFabricante2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigoFabricante2.setText("Cantidad:");

        lblCodigoFabricante4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigoFabricante4.setText("Precio:");

        lblCodigoFabricante6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigoFabricante6.setText("Código Tienda:");

        comboTienda.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N

        lblCodigoFabricante7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigoFabricante7.setText("Nombre:");

        ventaExitencia.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N

        ventaNombreCliente.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N

        ventaPrecio.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N

        ventaPrecio1.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N

        lblCodigoFabricante5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigoFabricante5.setText("Total a Pagar:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Producto", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblCodigoFabricante8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblCodigoFabricante8.setText("Lista de Articulos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNombre)
                                            .addComponent(lblCodigoFabricante)
                                            .addComponent(lblCodigoFabricante4))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblCodigoFabricante2)
                                            .addGap(17, 17, 17)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(lblCodigoFabricante5)))
                                .addGap(379, 379, 379)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigoFabricante6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(lblNombre1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ventaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(registrarProducto))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigoFabricante1)
                                    .addComponent(lblCodigoFabricante7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(codigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ventaNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ventaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ventaExitencia, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ventaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ventaPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(224, 224, 224)
                                .addComponent(lblCodigoFabricante8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblDescripcion)
                        .addGap(29, 29, 29)
                        .addComponent(productoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoFabricante6)
                        .addComponent(comboTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ventaFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoFabricante1)
                            .addComponent(codigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoFabricante7)
                            .addComponent(ventaNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoFabricante2)
                            .addComponent(ventaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoFabricante)
                            .addComponent(ventaExitencia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblCodigoFabricante4)
                                .addGap(44, 44, 44)
                                .addComponent(lblCodigoFabricante5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ventaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(ventaPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(lblCodigoFabricante8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcion)
                    .addComponent(productoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ventaCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventaCantidadActionPerformed

    private void registrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> codigoCliente;
    private javax.swing.JComboBox<String> comboTienda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCodigoFabricante;
    private javax.swing.JLabel lblCodigoFabricante1;
    private javax.swing.JLabel lblCodigoFabricante2;
    private javax.swing.JLabel lblCodigoFabricante4;
    private javax.swing.JLabel lblCodigoFabricante5;
    private javax.swing.JLabel lblCodigoFabricante6;
    private javax.swing.JLabel lblCodigoFabricante7;
    private javax.swing.JLabel lblCodigoFabricante8;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JComboBox<String> nombreProducto;
    private javax.swing.JTextField productoDescripcion;
    private javax.swing.JButton registrarProducto;
    private javax.swing.JTextField ventaCantidad;
    private javax.swing.JLabel ventaExitencia;
    private com.toedter.calendar.JDateChooser ventaFecha;
    private javax.swing.JLabel ventaNombreCliente;
    private javax.swing.JLabel ventaPrecio;
    private javax.swing.JLabel ventaPrecio1;
    // End of variables declaration//GEN-END:variables
}
