/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import ConexionBD.Conexion;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author danielferova
 */
public class NuevosPedidos extends javax.swing.JInternalFrame {
     PreparedStatement ps = null;
     
     ResultSet rs = null;
    /**
     * Creates new form NuevosPedidos
     */
    public NuevosPedidos() {
        initComponents();
        this.getContentPane().setBackground(Color.ORANGE);
        comboTienda();
        comboCodigoCliente();
        comboNombreP();
        
    }
    
        private void comboTienda() {

        Conexion conexion = new Conexion();
        ResultSet rs = conexion.getTabla("SELECT Id_Tienda FROM TIENDA");
        try {
            while (rs.next()) {
                comboTienda.addItem(rs.getString(1));
            }

        } catch (Exception e) {

        }
    }
        
            private void comboCodigoCliente() {

        Conexion conexion = new Conexion();
        ResultSet rs = conexion.getTabla("SELECT Nit_Cliente FROM CLIENTE");
        try {
            while (rs.next()) {
                codigoCliente.addItem(rs.getString(1));
            }

        } catch (Exception e) {

        }
    }
          private void comboNombreP() {

        Conexion conexion = new Conexion();
        ResultSet rs = conexion.getTabla("SELECT Nombre_Producto FROM PRODUCTO");
        try {
            while (rs.next()) {
                productoN.addItem(rs.getString(1));
            }

        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblCodigoFabricante = new javax.swing.JLabel();
        ventaCantidad = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        registrarProducto = new javax.swing.JButton();
        lblCodigoFabricante1 = new javax.swing.JLabel();
        codigoCliente = new javax.swing.JComboBox<>();
        lblNombre1 = new javax.swing.JLabel();
        ventaFecha = new com.toedter.calendar.JDateChooser();
        productoN = new javax.swing.JComboBox<>();
        lblCodigoFabricante2 = new javax.swing.JLabel();
        lblCodigoFabricante4 = new javax.swing.JLabel();
        lblCodigoFabricante6 = new javax.swing.JLabel();
        comboTienda = new javax.swing.JComboBox<>();
        lblCodigoFabricante7 = new javax.swing.JLabel();
        lblCodigoFabricante5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePedidos = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 101, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("NUEVOS PEDIDOS\n");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(254, 254, 254));
        lblNombre.setText("Producto:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        lblCodigoFabricante.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCodigoFabricante.setForeground(new java.awt.Color(254, 254, 254));
        lblCodigoFabricante.setText("Inventario:");
        getContentPane().add(lblCodigoFabricante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        ventaCantidad.setBackground(new java.awt.Color(254, 254, 254));
        ventaCantidad.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        ventaCantidad.setForeground(new java.awt.Color(1, 1, 1));
        ventaCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventaCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(ventaCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 240, -1));

        lblDescripcion.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(254, 254, 254));
        lblDescripcion.setText("Descripción:");
        getContentPane().add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        registrarProducto.setBackground(new java.awt.Color(1, 1, 1));
        registrarProducto.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        registrarProducto.setForeground(new java.awt.Color(254, 254, 254));
        registrarProducto.setText("Ingresar");
        registrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(registrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, 130, 60));

        lblCodigoFabricante1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCodigoFabricante1.setForeground(new java.awt.Color(254, 254, 254));
        lblCodigoFabricante1.setText("Código Cliente:");
        getContentPane().add(lblCodigoFabricante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 85, -1, -1));

        codigoCliente.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        getContentPane().add(codigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 77, 235, -1));

        lblNombre1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblNombre1.setForeground(new java.awt.Color(254, 254, 254));
        lblNombre1.setText("Fecha:");
        getContentPane().add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, 36));
        getContentPane().add(ventaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, 36));

        productoN.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        getContentPane().add(productoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 125, 235, -1));

        lblCodigoFabricante2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCodigoFabricante2.setForeground(new java.awt.Color(254, 254, 254));
        lblCodigoFabricante2.setText("Cantidad:");
        getContentPane().add(lblCodigoFabricante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        lblCodigoFabricante4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCodigoFabricante4.setForeground(new java.awt.Color(254, 254, 254));
        lblCodigoFabricante4.setText("Precio:");
        getContentPane().add(lblCodigoFabricante4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        lblCodigoFabricante6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCodigoFabricante6.setForeground(new java.awt.Color(254, 254, 254));
        lblCodigoFabricante6.setText("Código Tienda:");
        getContentPane().add(lblCodigoFabricante6, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 28, -1, -1));

        comboTienda.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        getContentPane().add(comboTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 28, 235, -1));

        lblCodigoFabricante7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCodigoFabricante7.setForeground(new java.awt.Color(254, 247, 247));
        lblCodigoFabricante7.setText("Nombre:");
        getContentPane().add(lblCodigoFabricante7, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 82, -1, -1));

        lblCodigoFabricante5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblCodigoFabricante5.setForeground(new java.awt.Color(254, 254, 254));
        lblCodigoFabricante5.setText("Total a Pagar:");
        getContentPane().add(lblCodigoFabricante5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jTablePedidos.setBackground(new java.awt.Color(254, 254, 254));
        jTablePedidos.setForeground(new java.awt.Color(1, 1, 1));
        jTablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio"
            }
        ));
        jTablePedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePedidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 620, 360));

        jTextField1.setBackground(new java.awt.Color(254, 254, 254));
        jTextField1.setForeground(new java.awt.Color(1, 1, 1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 170, 30));

        jTextField2.setBackground(new java.awt.Color(254, 254, 254));
        jTextField2.setForeground(new java.awt.Color(1, 1, 1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 170, -1));

        jTextField3.setBackground(new java.awt.Color(254, 254, 254));
        jTextField3.setForeground(new java.awt.Color(1, 1, 1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 150, -1));

        jTextField4.setBackground(new java.awt.Color(254, 254, 254));
        jTextField4.setText("jTextField4");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 240, -1));

        jTextField5.setBackground(new java.awt.Color(254, 254, 254));
        jTextField5.setForeground(new java.awt.Color(1, 1, 1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 450, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ventaCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventaCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventaCantidadActionPerformed

    private void registrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarProductoActionPerformed

    private void jTablePedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePedidosMouseClicked
        // TODO add your handling code here:
      //  int seleccion = jTablePedidos.rowAtPoint(evt.getPoint());
       // productoN.setText(String.valueOf(jTablePedidos.getValueAt(seleccion, 0)));
        
    }//GEN-LAST:event_jTablePedidosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> codigoCliente;
    private javax.swing.JComboBox<String> comboTienda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePedidos;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblCodigoFabricante;
    private javax.swing.JLabel lblCodigoFabricante1;
    private javax.swing.JLabel lblCodigoFabricante2;
    private javax.swing.JLabel lblCodigoFabricante4;
    private javax.swing.JLabel lblCodigoFabricante5;
    private javax.swing.JLabel lblCodigoFabricante6;
    private javax.swing.JLabel lblCodigoFabricante7;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JComboBox<String> productoN;
    private javax.swing.JButton registrarProducto;
    private javax.swing.JTextField ventaCantidad;
    private com.toedter.calendar.JDateChooser ventaFecha;
    // End of variables declaration//GEN-END:variables
}
