/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import ConexionBD.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danielferova
 */
public class VerTiempoEnvio extends javax.swing.JInternalFrame {
     PreparedStatement ps = null;
     ResultSet rs = null;
    /**
     * Creates new form Tiempo
     */
    public VerTiempoEnvio() {
        initComponents();
        this.getContentPane().setBackground(Color.ORANGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        buscarTiempo = new javax.swing.JButton();
        tienda1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTiempo = new javax.swing.JTable();
        buscarTiempo1 = new javax.swing.JButton();
        tienda2 = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 107, 0));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("TIEMPO\n");
        setPreferredSize(new java.awt.Dimension(1189, 775));

        lblNombre.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblNombre.setText("Busque código de la Tienda 1:");

        buscarTiempo.setBackground(new java.awt.Color(1, 1, 1));
        buscarTiempo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        buscarTiempo.setForeground(new java.awt.Color(254, 254, 254));
        buscarTiempo.setText("Buscar ");
        buscarTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTiempoActionPerformed(evt);
            }
        });

        tienda1.setBackground(new java.awt.Color(254, 254, 254));
        tienda1.setForeground(new java.awt.Color(1, 1, 1));

        tablaTiempo.setBackground(new java.awt.Color(254, 254, 254));
        tablaTiempo.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        tablaTiempo.setForeground(new java.awt.Color(1, 1, 1));
        tablaTiempo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tienda Origen", "Tienda Destino", "Tiempo En Días"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaTiempo);

        buscarTiempo1.setBackground(new java.awt.Color(1, 1, 1));
        buscarTiempo1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        buscarTiempo1.setForeground(new java.awt.Color(254, 254, 254));
        buscarTiempo1.setText("Ver Todo");
        buscarTiempo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTiempo1ActionPerformed(evt);
            }
        });

        tienda2.setBackground(new java.awt.Color(254, 254, 254));
        tienda2.setForeground(new java.awt.Color(1, 1, 1));

        lblNombre1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblNombre1.setText("Busque código de la Tienda 2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(466, 466, 466))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblNombre1))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tienda2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarTiempo1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tienda1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(buscarTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(tienda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarTiempo))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarTiempo1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tienda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre1)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTiempoActionPerformed
        // TODO add your handling code here:
        String campo = tienda1.getText();
        String campo1 = tienda2.getText();
        String where = "";
        
        if(!"".equals(campo)||!"".equals(campo1)){
            where = "WHERE Tienda_Origen = '" + campo + "' OR Tienda_Origen = '" + campo1 + "'" ;
               }
        try {
            DefaultTableModel model = new DefaultTableModel();
            tablaTiempo.setModel(model);
            Conexion con = new Conexion();
            Connection c = con.conectandoBase();
            
            String sql = "SELECT * FROM TIEMPO " + where ;
            ps = c.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadC = rsMd.getColumnCount();
            
            model.addColumn("ID");
            model.addColumn("Tienda 1");
            model.addColumn("Tienda 2");
            model.addColumn("Tiempo En Días");
       
            while(rs.next()){
                
                Object [] filas = new Object[cantidadC];
                for(int i = 0; i< cantidadC; i++){
                  filas[i] = rs.getObject(i + 1);
            }
                model.addRow(filas);
                limpiarCampos();
            }
            
        }catch(SQLException ex) {     
        }
        
    }//GEN-LAST:event_buscarTiempoActionPerformed

    //metodo para limpiar
    public void limpiarCampos(){
        tienda1.setText("");
        tienda2.setText("");
    }
    
    private void buscarTiempo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTiempo1ActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = new DefaultTableModel();
            tablaTiempo.setModel(model);
            Conexion con = new Conexion();
            Connection c = con.conectandoBase();
            
            String sql = "SELECT * FROM TIEMPO ";
            ps = c.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadC = rsMd.getColumnCount();
            
            model.addColumn("ID");
            model.addColumn("Tienda 1");
            model.addColumn("Tienda 2");
            model.addColumn("Tiempo En Días");
       
            while(rs.next()){
                
                Object [] filas = new Object[cantidadC];
                for(int i = 0; i< cantidadC; i++){
                  filas[i] = rs.getObject(i + 1);
            }
                model.addRow(filas);
            }
            
        }catch(SQLException ex) {     
        }
        
    }//GEN-LAST:event_buscarTiempo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarTiempo;
    private javax.swing.JButton buscarTiempo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JTable tablaTiempo;
    private javax.swing.JTextField tienda1;
    private javax.swing.JTextField tienda2;
    // End of variables declaration//GEN-END:variables
}
