/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazClientes;


import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;


/**
 *
 * @author danielferova
 */
public class ClientesMenu extends javax.swing.JFrame {
     String imagen =  "intelaf1.png";
      protected String nombreCliente;
    protected String nitCliente;
    /**
     * Creates new form ClientesMenu
     */
    public ClientesMenu(String nombreCliente, String nitCliente) {
        this.nombreCliente = nombreCliente;
        this.nitCliente = nitCliente;
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.ORANGE);
        cargarIcono(imagen);
    }
      public void cargarIcono(String NombreImagen)
    {
       ImageIcon imageIcon = new ImageIcon(getClass().getClassLoader().getResource(NombreImagen));
        ImageIcon imageIconFinal = new ImageIcon(imageIcon.getImage().getScaledInstance(intelaf.getWidth(), intelaf.getHeight(), Image.SCALE_DEFAULT));
        intelaf.setIcon(imageIconFinal);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        intelaf = new javax.swing.JLabel();
        menuTrabajadores = new javax.swing.JMenuBar();
        verCatalogo = new javax.swing.JMenu();
        ver = new javax.swing.JMenuItem();
        verPedido = new javax.swing.JMenu();
        rastrear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabajador ");
        setBackground(new java.awt.Color(0, 255, 51));
        setForeground(new java.awt.Color(102, 255, 51));

        escritorio.setBackground(new java.awt.Color(254, 183, 25));
        escritorio.setForeground(new java.awt.Color(51, 255, 255));

        intelaf.setText("Icono");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(486, Short.MAX_VALUE)
                .addComponent(intelaf, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(459, 459, 459))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(intelaf, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        menuTrabajadores.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N

        verCatalogo.setBackground(new java.awt.Color(254, 254, 254));
        verCatalogo.setForeground(new java.awt.Color(5, 0, 0));
        verCatalogo.setText("CATÁLOGO DE PRODUCTOS");
        verCatalogo.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        ver.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        ver.setText("Ver Catálago");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });
        verCatalogo.add(ver);

        menuTrabajadores.add(verCatalogo);

        verPedido.setBackground(new java.awt.Color(254, 254, 254));
        verPedido.setForeground(new java.awt.Color(1, 1, 1));
        verPedido.setText("RASTREO DE PEDIDOS");
        verPedido.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N

        rastrear.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        rastrear.setText("BuscarPedido");
        rastrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rastrearActionPerformed(evt);
            }
        });
        verPedido.add(rastrear);

        menuTrabajadores.add(verPedido);

        setJMenuBar(menuTrabajadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rastrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rastrearActionPerformed
      PedidosRastreo rastreoPedido = new PedidosRastreo();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(rastreoPedido);
      rastreoPedido.show();
    }//GEN-LAST:event_rastrearActionPerformed

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
      ClientesCatalogo catalogo = new ClientesCatalogo();
      escritorio.removeAll();
      escritorio.updateUI();
      escritorio.add(catalogo);
      catalogo.show();
    }//GEN-LAST:event_verActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    public javax.swing.JLabel intelaf;
    private javax.swing.JMenuBar menuTrabajadores;
    private javax.swing.JMenuItem rastrear;
    private javax.swing.JMenuItem ver;
    private javax.swing.JMenu verCatalogo;
    private javax.swing.JMenu verPedido;
    // End of variables declaration//GEN-END:variables
}
